# Used to define the location of run.info file where run number and previous run conditions are stored
export DAQ_CONFIG=/local/home/administrator/FeminosDAQ

# Used to define where the rawdata files generated by the DAQ will be stored
export RAWDATA_PATH=/local/rawData/

# The PATH to add files to analyse using quickAnaREST automatically generated by the DAQ when a file is closed.
export FILES_TO_ANALYSE_PATH=$HOME/git/quickAnaREST/filesToAnalyse/

# variables to control the submission of entries to the ELOG
export ELOG_ACTIVE=NO
export ELOG_IP=132.166.30.28
export ELOG_PORT=8080
export ELOG_NAME=PANDAXIII
