name: CMake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          miniforge-variant: Miniforge3
          use-mamba: true

      - name: Install dependencies
        run: |
          mamba install root

      - name: ROOT info
        run: |
          which root
          root-config --version
          root-config --cflags

      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -S ${{github.workspace}} -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release
          cmake --build ${{github.workspace}}/build

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: mclient
          path: ${{github.workspace}}/build/mclient
